services:
  individual_patients:
    build:
        context: .
        dockerfile: dashboards/individual_patients/Dockerfile
    ports:
      - "9999:9999"
  cohort_concentrations:
    build:
      context: .
      dockerfile: dashboards/cohort_concentrations/Dockerfile
    ports:
      - "9999:9999"
